### PR TITLE
Map Salus stack in a fixed VA address.

### LINKED ISSUE #240: Insert guard pages below per-CPU stacks
@rajnesh-kanwal encountered a panic in #239 that turned out to be due to a stack overflow on one CPU scribbling over the `PerCpu` struct of another CPU. We should really be inserting guard pages between the CPU stacks so that we can get an easy to diagnose page-fault.

### PR DESCRIPTION
**Pull request by glg-rv**
Small patches, profound changes. Fixes #240 

This PR maps salus stack in a VA space. Initialization happens now in two stages.

The first stage (init) is when everything (including stack) is mapped in a contiguous physical mapping in the VA.
The second stage (launch) is called once the page table and the va-mapped stack has been setup.

Ideally, we whould like to push as much as possible into the second stage. But this is future work and requires more consideration.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -329,17 +335,22 @@ extern "C" fn kernel_init(_hart_id: u64, _fdt_addr: u64) {
     poweroff();
 }
 
+#[cfg(test)]
+#[no_mangle]
+extern "C" fn primary_launch() {}
```
Comment (rbradford) [inline src/main.rs:340]: Would you consider using the naming `{primary,secondary}_stage{1,2}` as then you don't need to remember if init comes before launch?

File: src/hyp_map.rs [hunk 2]
```diff
@@ -35,6 +35,9 @@ type UmodeElfRegionsVec = ArrayVec<UmodeElfRegion, MAX_UMODE_ELF_REGIONS>;
 // Hw map regions vector.
 type HwMapRegionsVec = ArrayVec<HwMapRegion, MAX_HW_MAP_REGIONS>;
 
+// Global reference to the Hypervisor Map.
```
Comment (rbradford) [inline src/hyp_map.rs:38]: nit: Perhaps this commit message should start with `hyp_map`. Also would you consider adding why moving it is a good idea?

File: src/main.rs (hunk 1 above)
Comment (glg-rv) [reply src/main.rs:340]: Not having strong opinion on  names, but believing that launch happens before init is a bit of a stretch.

Thought initially about stage0,1 but decided to do this essentially for fishing for names.

File: src/smp.rs [hunk 3]
```diff
@@ -41,23 +41,14 @@ static PER_CPU_BASE: Once<SupervisorPageAddr> = Once::new();
 impl PerCpu {
     /// Initializes the `PerCpu` structures for each CPU, taking memory from `mem_map`. This (the
     /// boot CPU's) per-CPU area is initialized and loaded into TP as well.
-    pub fn init(boot_hart_id: u64, mem_map: &mut HwMemMap) {
+    pub fn init(boot_hart_id: u64, hyp_mem: &mut HypPageAlloc) {
```
[the remark this answers is not in the document]
Comment (glg-rv) [reply src/smp.rs:49]: Literally the title of the commit title is: "with the allocator", rather than the hw map. This has been a slowly moving process (that started on per-cpu page table) to move allocation from map to allocator. I think it's clear.

File: src/hyp_map.rs (hunk 2 above)
Comment (glg-rv) [reply src/hyp_map.rs:38]: I don't think the move is per se important in rust. It was just a clean up on the way code has evolved since the creation.

File: src/main.rs (hunk 1 above)
Comment (glg-rv) [reply src/main.rs:340]: current thinking (offline discussion with @rbradford) is to go towards `_init` and `_main`, almost crt-like. Open to change.

File: src/hyp_map.rs [hunk 4]
```diff
@@ -585,7 +585,11 @@ impl HypMap {
     }
 
     /// Creates a new page table based on this memory map.
-    pub fn new_page_table(&self, hyp_mem: &mut HypPageAlloc) -> HypPageTable {
+    pub fn new_page_table(
```
Comment (rbradford) [inline src/hyp_map.rs:588]: nit: This commit message needs s/launch/main/ now that that nomenclature is used.

File: src/smp.rs [hunk 5]
```diff
@@ -41,23 +41,14 @@ static PER_CPU_BASE: Once<SupervisorPageAddr> = Once::new();
...
-            .regions()
-            .find(|r| r.region_type() == HwMemRegionType::Available && r.size() >= total_size)
-            .map(|r| r.base())
-            .expect("Not enough free memory for per-CPU area");
-        mem_map
-            .reserve_region(
-                HwReservedMemType::HypervisorPerCpu,
-                RawAddr::from(pcpu_base),
-                total_size,
-            )
```
Comment (abrestic-rivos) [inline src/smp.rs:59]: i guess we can remove the per-CPU region type from `HwMemMap` now.

File: src/hyp_layout.rs [hunk 6]
```diff
@@ -21,7 +21,18 @@
...
 // +-------------------------+ UMODE_INPUT_START
 // | Umode Input Area        |
-// +-------------------------+ +UMODE_INPUT_SIZE
+// +-------------------------+ +UMODE_INPUT_SIZE (UMODE_INPUT_END, UMODE_END)
+// | (unused 4Mb)            |
+// +-------------------------+ HYP_STACKBTM_MIN
+// | (unused)                |
+// +-------------------------+ HYP_STACKTOP - stack size [1]
+// | Hypervisor Stack        |
+// +-------------------------+ HYP_STACK_TOP (0xffff_ffff_ffff_f000)
```
Comment (abrestic-rivos) [inline src/hyp_layout.rs:30]: nit: inconsistency between `STACKTOP` and `STACK_TOP`. i'd prefer the latter.

File: src/hyp_layout.rs [hunk 7]
```diff
@@ -75,6 +86,17 @@ const_assert!(PageSize::Size4k.is_aligned(UMODE_INPUT_START));
 /// Size of the U-mode Input Region.
 pub const UMODE_INPUT_SIZE: u64 = 4 * 1024;
 const_assert!(PageSize::Size4k.is_aligned(UMODE_INPUT_SIZE));
+/// End of the U-mode Input Region.
+const UMODE_INPUT_END: u64 = UMODE_INPUT_START + UMODE_INPUT_SIZE;
+/// Last U-mode address.
+const UMODE_END: u64 = UMODE_INPUT_END;
+
+/// The lowest possible kernel stack address.
+pub const HYP_STACKBTM_MIN: u64 = UMODE_END + 4 * 1024 * 1024;
```
Comment (abrestic-rivos) [inline src/hyp_layout.rs:95]: is the difference between "bottom min" and `top - stack size" because cpu0 has a different stack size?

File: src/hyp_layout.rs [hunk 8]
```diff
@@ -75,6 +86,17 @@ const_assert!(PageSize::Size4k.is_aligned(UMODE_INPUT_START));
...
+/// Address of the hypervisor stack top.
+pub const HYP_STACKTOP: u64 = 0xffff_ffff_ffff_f000;
```
Comment (abrestic-rivos) [inline src/hyp_layout.rs:97]: i'd make the stack alignment something greater than 4kb. say 16kb, or 2MB, in order to be able to take advantage of Svnapot or (unlikely) huge PTEs.

File: src/hyp_map.rs [hunk 9]
```diff
@@ -323,6 +325,63 @@ impl UmodeInputRegion {
...
+        let pte_fields = PteFieldBits::leaf_with_perms(PteLeafPerms::RW);
+        // Unmap stack pages from the 1:1 map.
+        for _ in sv48
+            .unmap_range(
+                self.paddr.as_supervisor_virt(),
+                PageSize::Size4k,
+                self.page_count,
+            )
+            .unwrap()
+        {}
```
Comment (abrestic-rivos) [inline src/hyp_map.rs:363]: instead of an empty loop, you can use `count()` to consume the iterator.

File: src/hyp_map.rs [hunk 10]
```diff
@@ -323,6 +325,63 @@ impl UmodeInputRegion {
     }
 }
 
+/// Represents a hypervisor stack region.
+pub struct HypStackRegion {
+    vaddr: PageAddr<SupervisorVirt>,
+    paddr: PageAddr<SupervisorPhys>,
+    page_count: u64,
```
Comment (abrestic-rivos) [inline src/hyp_map.rs:332]: once all stacks are the same size, we should be able to avoid storing vaddr & page_count for each CPU rigth?

File: src/main.rs [hunk 11]
```diff
@@ -559,20 +559,22 @@ extern "C" fn primary_init(hart_id: u64, fdt_addr: u64) -> CpuLaunch {
...
+        sp: this_cpu.stack_top(),
     }
 }
 
 /// Start salus on the bootstrap CPU. This is called once we switch to the hypervisor page-table.
 #[no_mangle]
 extern "C" fn primary_main() {
+    let sp: u64;
+    // Safe since there is no memory access.
+    unsafe { core::arch::asm!("mv {rs}, sp", rs = out(reg) sp) };
```
Comment (abrestic-rivos) [inline src/main.rs:575]: the asm shuld have "nomem" to indicate the absence of a memory clobber then. (here and below)

File: src/smp.rs [hunk 12]
```diff
@@ -18,6 +20,8 @@ use crate::vm_id::VmIdTracker;
 
 // The secondary CPU entry point, defined in start.S.
```
Comment (abrestic-rivos) [inline src/smp.rs:21]: move this comment to be over `_secondary_start` because it doesn't really apply to `_stack_*`

File: src/smp.rs [hunk 13]
```diff
@@ -30,10 +34,11 @@ pub struct PerCpu {
     page_table: HypPageTable,
     umode_task: Once<RefCell<UmodeTask>>,
     online: Once<bool>,
+    stack_top: u64,
 }
 
 /// The number of pages we allocate per CPU: the CPU's stack + it's `PerCpu` structure.
-const PER_CPU_PAGES: u64 = 8;
+const PER_CPU_PAGES: u64 = 0x80;
```
Comment (abrestic-rivos) [inline src/smp.rs:41]: 512k per CPU?!

File: src/smp.rs [hunk 14]
```diff
@@ -54,15 +62,45 @@ impl PerCpu {
...
+        let mut pcpu_stacks =
+            pcpu_pages.into_chunks_iter(core::num::NonZeroU64::new(PER_CPU_PAGES).unwrap());
         for i in 0..cpu_info.num_cpus() {
             let cpu_id = CpuId::new(i);
+            // Unwrap okay. We allocated the area `with num_cpus() * PER_CPU_PAGES` pages.
+            let pcpu_stack = pcpu_stacks.next().unwrap();
+            // Boot CPU is special. Doesn't use the PCPU_BASE area as stack, only for the PCPU area.
+            // TODO: Do not allocate PCPU area for boot cpu.
+            let stack_pages = if cpu_id == boot_cpu {
+                Self::boot_cpu_stack()
```
Comment (abrestic-rivos) [inline src/smp.rs:75]: i think we discussed this offline and i'm fuzzy on the details, but why can't we switch tthe boot CPU over to use a stack from `pcpu_stacks`? the whole boot cpu having a different stack size than the secondary cpus thing has hidden a couple of bugs from us so far. (it would also reduce all the special-casing you have to do here.)

File: src/smp.rs [hunk 15]
```diff
@@ -54,15 +62,45 @@ impl PerCpu {
...
+                        pcpu_stack.len(),
+                    )
+                    .unwrap()
+                }
+            };
+            let stack_top = if cpu_id == boot_cpu {
+                crate::hyp_layout::HYP_STACKTOP
+            } else {
+                // Secondary CPUs have PerCpu structure at top of stack.
+                crate::hyp_layout::HYP_STACKTOP - core::mem::size_of::<PerCpu>() as u64
```
Comment (abrestic-rivos) [inline src/smp.rs:94]: so by keeping `PerCpu` on the stack, we effectively make it impossible for one CPU to access another's `PerCpu`. we don't use it for inter-processor communication currently, but it's not unreasonable that we would want to do so in the future. have you considered putting the `PerCpu`s in a global array instead? i only put them on the stack to begin with because it was convenient to be able to have one pointer for both the initial sp and `PerCpu` when launching a secondary CPU.

File: src/smp.rs (hunk 5 above)
Comment (glg-rv) [reply src/smp.rs:59]: Agreed.

File: src/hyp_layout.rs (hunk 6 above)
Comment (glg-rv) [reply src/hyp_layout.rs:30]: Whops.

File: src/hyp_layout.rs (hunk 7 above)
Comment (glg-rv) [reply src/hyp_layout.rs:95]: Yes, or rather, was. I want to fix that in the next PR, where I force the stack to be the same on all CPUs (to ease calculation on trap handler for stack bottom). This was just a check on the bootstrap CPU stack (that is controlled at the moment by the linker script)

File: src/hyp_map.rs (hunk 9 above)
Comment (glg-rv) [reply src/hyp_map.rs:363]: Ack.

File: src/main.rs (hunk 11 above)
Comment (glg-rv) [reply src/main.rs:575]: Sure.

File: src/smp.rs (hunk 12 above)
Comment (glg-rv) [reply src/smp.rs:21]: Right.

File: src/smp.rs (hunk 13 above)
Comment (glg-rv) [reply src/smp.rs:41]: Yes. Our stack usage isn't great. Mapping takes quite a lot. And when we run in Debug Mode we're essentially all over the place when it come to stack usage.

I am due to restore my previous stack analysis once this is over.

File: src/smp.rs (hunk 14 above)
Comment (glg-rv) [reply src/smp.rs:75]: Sure, the problem with this is that we would still need a (huge) stack at the beginning (init phase). That stack is allocated by the linker.

I implemented both ways, one where the bootstrap CPU used this PerCPu stack (which simplifies things quite a lot on a architectural point of view) but that wastes the original init-time stack memory.

With this, we can have a following PR that saves stack memory by changing this `smp` code to not allocate a full blown CPU stack just for the PerCpu data stucture. There are various ways to achieve this, non particularly difficult.

File: src/smp.rs (hunk 15 above)
Comment (glg-rv) [reply src/smp.rs:94]: So the trick here is that only the CPU using the stack doesn't have its stack mapped in the 1:1. Which is why the CPU bootstrap can wait for the CPU to go online in `start_secondary_cpus` -- which effectively requires access of other CPU's PerCpu from the bootstrap CPU.

My comment above (about removing the need for a full stack for the Bootstrap PerCpu Data structure) implies exactly what you suggest. I had implemented it, but I wanted this patch to be as simple as possible and use the current SMP architecture to review the mechanism of stack allocation.

File: src/smp.rs (hunk 5 above)
Comment (glg-rv) [reply src/smp.rs:59]: Done.

File: src/hyp_layout.rs (hunk 6 above)
Comment (glg-rv) [reply src/hyp_layout.rs]: Fixed.

File: src/hyp_layout.rs (hunk 7 above)
Comment (glg-rv) [reply src/hyp_layout.rs]: All CPUs have the same size in the new iteration.

File: src/hyp_layout.rs (hunk 8 above)
Comment (glg-rv) [reply src/hyp_layout.rs]: Aligned at 2M.

File: src/smp.rs (hunk 14 above)
Comment (glg-rv) [reply src/smp.rs:73]: Now PerCpu data and stack are separate.

File: src/smp.rs (hunk 15 above)
Comment (glg-rv) [reply src/smp.rs]: PerCpu not on stack anymore.

File: src/smp.rs (hunk 12 above)
Comment (glg-rv) [reply src/smp.rs]: Done.

**Comment by glg-rv** [comment]
Relatively major update. Originally I thought of this patch as something that wouldn't change `smp.rs` fundamentally in order to focus on the stack mapping size. Since the issues that this created came up in the review, decided to make this PR a bit more complex.

This new version of the PR forces all CPUs to have the same stack size. This makes the layout fixed and also simplifies the code.

PerCpu data doesn't live in the stack anymore. This slightly changes the AP bootstrap code because SP and TP are not the same anymore. As an advantage, we do not allocate an extra stack just for the bootstrap CPU PerCpu.

File: src/hyp_map.rs [hunk 16]
```diff
@@ -254,6 +257,72 @@ impl UmodeElfRegion {
...
 }
 
+/// The U-mode Input Region is a private region of the page table used by the hypervisor to pass
+/// data to the current U-mode operation. This avoids mapping hypervisor data directly in
+/// U-mode. This area is written by the hypervisor and mapped read-only in U-mode.
+struct UmodeInputRegion {
+    /// Volatile Slice used to write to this area from the hypervisor.
+    vslice: VolatileSlice<'static>,
+}
+
```
Comment (rbradford) [inline src/hyp_map.rs:268]: nit: If you don't need any other members then you can use the alternative `struct UmodeInputRegion(VolatileSlice<'static>)` syntax and then refer to it as `.0`

File: src/hyp_map.rs [hunk 17]
```diff
@@ -254,6 +257,72 @@ impl UmodeElfRegion {
...
+        let vslice = unsafe {
+            VolatileSlice::from_raw_parts(start.raw().bits() as *mut u8, UMODE_INPUT_SIZE as usize)
+        };
+        Self { vslice }
+    }
+
+    // Writes `data` in the current CPU's U-mode Input Region.
+    fn store<T: DataInit>(&mut self, data: T) -> Result<(), Error> {
+        let vref = self.vslice.get_ref(0).map_err(Error::UmodeInput)?;
+        vref.store(data);
```
Comment (rbradford) [inline src/hyp_map.rs:317]: nit: Is it a good idea to zero the area before writing in case the new data is smaller than the old?

File: src/hyp_map.rs (hunk 16 above)
Comment (rbradford) [reply src/hyp_map.rs:268]: I just realised that this a rearrangment commit so you can disregard these comments as this is not new code (or consider fixing in another commit if you think they're appropriate :-) )

File: src/smp.rs [hunk 18]
```diff
@@ -30,11 +35,9 @@ pub struct PerCpu {
     page_table: HypPageTable,
     umode_task: Once<RefCell<UmodeTask>>,
     online: Once<bool>,
+    stack_top_addr: SupervisorPageAddr,
```
Comment (rbradford) [inline src/smp.rs:38]: Could you store `HypStackRegion` here instead and add to it accessors for start/end of stack as well as getting it as a slice. @stillson could then use that in the backtrace PR.

File: src/smp.rs [hunk 19]
```diff
@@ -43,54 +46,119 @@ impl PerCpu {
...
+    }
 
-        let me = Self::this_cpu();
-        me.set_online();
+    fn boot_cpu_stack() -> SequentialPages<InternalDirty> {
+        // Get the pages of the current stack as created by the linker.
+        // Safe because these are linker created variables.
+        let stack_start = unsafe { core::ptr::addr_of!(_stack_start) as u64 };
+        let stack_end = unsafe { core::ptr::addr_of!(_stack_end) as u64 };
+        let stack_startaddr = PageAddr::new(RawAddr::supervisor(stack_start))
```
Comment (rbradford) [inline src/smp.rs:136]: In cases like this I think variable shadowing is fine it would improve the readability.

File: src/smp.rs (hunk 18 above)
Comment (glg-rv) [reply src/smp.rs:38]: Well, that patch will have to use the virtual mapping not the physical one. Virtual mapping are static, which is one of the feature of the patch. I am not particularly happy about adding this field, but I needed between creation and initialization of CPUs, so that was good enough.

Regarding HypStackRegion, no, if we need the hypstack region we should access it from the HypMap, not here.

File: src/smp.rs (hunk 19 above)
Comment (glg-rv) [reply src/smp.rs:136]: Readability is subjective. :-)

I find it more readable to step things in small steps. But what you're suggesting is more in line with the rust way so I'll happily change that.

File: src/hyp_map.rs (hunk 17 above)
Comment (glg-rv) [reply src/hyp_map.rs:317]: The guarantee that this is cleared is due on u-mode execute request. I understand that this might not sound straightforward, but this piece of code (as you correctly noted, this is just a move) was a complex interaction between three systems, so I preferred to have the mechanism here and the checking elsewhere.

In case you are going to go with a type that destroy on drop, that was one of my iterations during review. :-)

File: src/hyp_map.rs (hunk 16 above)
Comment (glg-rv) [reply src/hyp_map.rs:268]: Heh, yes. In general I don't mind named structs. I find them simpler. Do you have any opinion on why would be better to have in the format you suggest?

Comment (rbradford) [reply src/hyp_map.rs:268]: I think it's just a style/convention thing. If the struct is really a wrapper around another type (so you can implement methods or traits) then I think the tuple format is preferred. If it's truly a new struct that only happens to have one member then named member structs are the norm.

File: src/smp.rs (hunk 14 above)
Comment (abrestic-rivos) [reply src/smp.rs:73]: understood re: not wanting to waste memory. but should we at least clamp the size of the boot CPU's stack when we set up the VA mapping so that all CPUs have the same stack size? i really want to get rid of this situation where things sometimes work because they're run on the boot CPU vs secondary CPU.

**Review by abrestic-rivos — COMMENTED** [review]
just a couple minor comments left, otherwise lgtm.

File: src/smp.rs [hunk 20]
```diff
@@ -43,54 +46,119 @@ impl PerCpu {
...
+        // Allocate memory for per-CPU structures.
+        let pcpu_size = core::mem::size_of::<PerCpu>() as u64 * cpu_info.num_cpus() as u64;
         let pcpu_pages =
-            hyp_mem.take_pages_for_hyp_state(PageSize::num_4k_pages(total_size) as usize);
+            hyp_mem.take_pages_for_hyp_state(PageSize::num_4k_pages(pcpu_size) as usize);
         let pcpu_base = pcpu_pages.base();
         PER_CPU_BASE.call_once(|| pcpu_base);
 
+        // Allocate memory for the secondary CPUs stack.
+        let stacks_page_count = HYP_STACK_PAGES * cpu_info.num_cpus() as u64 - 1;
```
[the remark this answers is not in the document]
Comment (glg-rv) [reply src/smp.rs:61]: Whops! This hurts. Thank you, will fix. :-)

File: src/smp.rs (hunk 14 above)
Comment (glg-rv) [reply src/smp.rs:73]: I do that in HypMap on stack region. I return InvalidStackSize if the linker allocated stack is not _exactly_ `HYP_STACK_PAGES`. But thinking about it, possibly clamping it afterwards could be more generic and allows us a bigger boot stack than runtime requires. Would be wasted memory though.

Although, I kind of like to remove any power to the linker and check at runtime if it was built properly.

File: src/hyp_map.rs (hunk 16 above)
Comment (glg-rv) [reply src/hyp_map.rs:268]: I think I'll leave it like this for now. In a way there's more to the UmodeInputRegion than a slice, although that's what it is in practice.

File: src/smp.rs (hunk 19 above)
Comment (glg-rv) [reply src/smp.rs]: Changed. Put unsafe across the pageaddr block. Let me know what you think.

File: src/hyp_layout.rs [hunk 21]
```diff
@@ -76,6 +82,25 @@ const_assert!(PageSize::Size4k.is_aligned(UMODE_INPUT_START));
 pub const UMODE_INPUT_SIZE: u64 = 4 * 1024;
 const_assert!(PageSize::Size4k.is_aligned(UMODE_INPUT_SIZE));
 
+/// Address of the hypervisor stack top.
+#[allow(dead_code)]
```
[the remark this answers is not in the document]
Comment (glg-rv) [reply src/hyp_layout.rs]: I'll leave it as is for now, but will do that in future PRs.

File: src/smp.rs (hunk 20 above)
[the remark this answers is not in the document]
Comment (glg-rv) [reply src/smp.rs]: Fixed.

**Review by abrestic-rivos — APPROVED** [review]
